# Jupyter Notebook for downloading required datasets

In [2]:
import tensorflow_datasets as tfds

2023-01-02 18:44:13.461846: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-02 18:44:14.032146: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/rgroh/anaconda3/envs/evo_nas/lib/
2023-01-02 18:44:14.032221: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/rgroh/anaconda3/envs/evo_nas/lib/
2023-01-02 18:44:14.032228: W tensorflow/compile

## Speech Commands

In [10]:
ds, info = tfds.load("speech_commands", data_dir='.', split='test',as_supervised=True, download=True, with_info=True)

In [16]:
for idx, d in enumerate(tfds.as_numpy(ds)):
    print(d)
    if idx == 10:
        break

(array([  -1,   -2,   -2, ..., -136, -170, -203], dtype=int16), 7)
(array([ 0,  1,  3, ..., -4, -4, -4], dtype=int16), 2)
(array([ 12,  23,  25, ..., -15, -20, -15], dtype=int16), 6)
(array([ 6,  5,  4, ..., 40, 43, 51], dtype=int16), 8)
(array([-1, -2, -2, ...,  3,  3,  3], dtype=int16), 5)
(array([   0,    0,    0, ..., 3436, 3313, 3117], dtype=int16), 0)
(array([17, 35, 25, ..., 38, 24,  6], dtype=int16), 8)
(array([ -5, -23, -33, ...,   7, -27, -25], dtype=int16), 9)
(array([-20, -32, -28, ...,   0,   0,   0], dtype=int16), 4)
(array([1, 1, 1, ..., 2, 1, 3], dtype=int16), 3)
(array([ 20,  28,  84, ..., 159,  84,  10], dtype=int16), 11)


In [17]:
info

tfds.core.DatasetInfo(
    name='speech_commands',
    full_name='speech_commands/0.0.3',
    description="""
    An audio dataset of spoken words designed to help train and evaluate keyword
    spotting systems. Its primary goal is to provide a way to build and test small
    models that detect when a single word is spoken, from a set of ten target words,
    with as few false positives as possible from background noise or unrelated
    speech. Note that in the train and validation set, the label "unknown" is much
    more prevalent than the labels of the target words or background noise.
    One difference from the release version is the handling of silent segments.
    While in the test set the silence segments are regular 1 second files, in the
    training they are provided as long segments under "background_noise" folder.
    Here we split these background noise into 1 second clips, and also keep one of
    the files for the validation set.
    """,
    homepage='https://arxiv.or

In [26]:
import serial
import time

In [28]:

with serial.Serial("/dev/ttyACM3", 115200, timeout=1) as ser:
    for _ in range(5000):
        line = ser.readline()
        time.sleep(0.05)
        if line != b'':
            print(str(line))

b'InfTime: 02118\r\r\n'
b'InfTime: 02117\r\r\n'
b'InfTime: 02119\r\r\n'
b'InfTime: 02119\r\r\n'
b'InfTime: 02117\r\r\n'
b'InfTime: 02119\r\r\n'


KeyboardInterrupt: 

In [8]:
for _ in range(1000):
    with serial.Serial("/dev/ttyACM3", 115200, timeout=1) as ser:
        if ser.inWaiting() > 0: 
            data = ser.read(ser.inWaiting())
            print(data)
            break
        
        time.sleep(0.01)